# Generated by Django 4.2 on 2023-04-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_project_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
