# Generated by Django 4.2 on 2023-04-27 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_manager': True}, null=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
