# Generated by Django 4.2.1 on 2023-05-25 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0006_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="managers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудники",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="projects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.project",
                verbose_name="Проекты",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_manager": True},
                null=True,
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначено",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                limit_choices_to={"is_employee": True},
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначено",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"is_manager": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                default=2,
                verbose_name="Приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="management.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("inprogress", "In Progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
