# Generated by Django 4.2.1 on 2023-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0011_taskcompletionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcompletionrequest",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
