# Generated by Django 4.2.1 on 2023-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0012_projectcompletionrequest_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcompletionrequest",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
    ]
