# Generated by Django 4.2.1 on 2023-05-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0013_taskcompletionrequest_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcompletionrequest",
            name="rating",
            field=models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
        ),
    ]
