# Generated by Django 4.2.1 on 2023-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0014_projectcompletionrequest_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rating_count",
            field=models.IntegerField(default=0, verbose_name="Количество оценок"),
        ),
    ]
