# Generated by Django 4.2.1 on 2023-05-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0017_remove_project_rating_count_projectapprovalrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectapprovalrequest",
            options={
                "verbose_name": "Запрос на одобрение проекта",
                "verbose_name_plural": "Запросы на одобрение проекта",
            },
        ),
        migrations.AddField(
            model_name="projectapprovalrequest",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Одобрено"),
        ),
        migrations.AlterField(
            model_name="projectapprovalrequest",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="projectapprovalrequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.project",
                verbose_name="Проект",
            ),
        ),
    ]
