# Generated by Django 4.2.1 on 2023-05-28 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0018_alter_projectapprovalrequest_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectApprovalRequest",
        ),
    ]
