# Generated by Django 4.2.1 on 2023-05-28 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0020_project_approved_by_admin_projectapprovalrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectApprovalRequest",
        ),
    ]
