# Generated by Django 4.2.1 on 2023-05-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0021_delete_projectapprovalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата начала"
            ),
        ),
    ]
