# Generated by Django 4.2.1 on 2023-05-31 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0023_alter_project_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "verbose_name": "Проекты менеджера",
                "verbose_name_plural": "Проекты менеджеров",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Задача сотрудника",
                "verbose_name_plural": "Задачи сотрудников",
            },
        ),
    ]
