# Generated by Django 4.2.1 on 2023-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0025_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcompletionrequest",
            name="proof",
            field=models.FileField(
                blank=True, upload_to="proofs/%Y/%m/%d", verbose_name="Доказательство"
            ),
        ),
    ]
