# Generated by Django 4.2.1 on 2023-05-25 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_customuser_address_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                default="Unknown",
                help_text="address",
                max_length=255,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="departament",
            field=models.CharField(
                default="Unknown", max_length=255, verbose_name="Отдел"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/%Y/%m/%d",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_employee",
            field=models.BooleanField(
                default=False, verbose_name="Является сотрудником"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(
                default=False, verbose_name="Является менеджером"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                default="Unknown",
                help_text="+992---",
                max_length=255,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="request_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата запроса"),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Одобрен"),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="declined",
            field=models.BooleanField(default=False, verbose_name="Отклонен"),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_request",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
