# Generated by Django 4.2.1 on 2023-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_customuser_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rate",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
    ]
