# Generated by Django 4.2.1 on 2023-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_customuser_rating_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="rating_count",
        ),
    ]
